version: '3.5'

networks:
  cluster-network:

services:
  json_parser:
    networks:
      cluster-network:
        aliases:
          - json_parser
    image: magkairatov/project_bi_msv023:latest
    container_name: json_parser
    restart: unless-stopped
    environment:
      LOG_LEVEL: "INFO"
      JAVA_OPTS: "-XX:+UseG1GC -Xms256m -Xmx256m"
      BOOTSTRAP_SERVERS: "broker1:9092,broker2:9092,broker3:9092"
      SCHEMA_REGISTRY_URL: "http://zookeep:8081"

